// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANmdEoVE49Ur6gPmnSoFMlfyHhZvn1Fbc',
    appId: '1:357307858830:web:fde4b58171e64022beaedf',
    messagingSenderId: '357307858830',
    projectId: 'smart-soft-babfa',
    authDomain: 'smart-soft-babfa.firebaseapp.com',
    storageBucket: 'smart-soft-babfa.appspot.com',
    measurementId: 'G-3NQW6R9P2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeSNDL-Oal-yCvckvd2K881B0q6C7pOWo',
    appId: '1:357307858830:android:31bda3dfdfef59a2beaedf',
    messagingSenderId: '357307858830',
    projectId: 'smart-soft-babfa',
    storageBucket: 'smart-soft-babfa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHK-7SgYqa1ivoCkoRnodXh1UL7e1RrcU',
    appId: '1:357307858830:ios:2ec6638f99dd8136beaedf',
    messagingSenderId: '357307858830',
    projectId: 'smart-soft-babfa',
    storageBucket: 'smart-soft-babfa.appspot.com',
    iosBundleId: 'com.example.smartSoft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHK-7SgYqa1ivoCkoRnodXh1UL7e1RrcU',
    appId: '1:357307858830:ios:2681677ce9073414beaedf',
    messagingSenderId: '357307858830',
    projectId: 'smart-soft-babfa',
    storageBucket: 'smart-soft-babfa.appspot.com',
    iosBundleId: 'com.example.smartSoft.RunnerTests',
  );
}
